name: Go
on:
  release:
    types: [published]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    - name: Build
      run: go env -w GOOS=linux && go env -w GOARCH=amd64 && go env -w  GOPROXY=https://goproxy.io  && go build -o sshcmd -v && chmod a+x sshcmd
    
    - name: Build Arm
      run: go env -w GOOS=linux && go env -w GOARCH=arm64 && go env -w  GOPROXY=https://goproxy.io  && go build -o sshcmd-arm -v && chmod a+x sshcmd

    - name: Create Release
      uses: JasonEtco/upload-to-release@master
      with:
        args: sshcmd application/octet-stream
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Create Arm Release
      uses: JasonEtco/upload-to-release@master
      with:
        args: sshcmd-arm64 application/octet-stream
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
